In [3]:
from scipy.cluster import hierarchy
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
data = pd.read_csv("/home/jorge/tfm-jvm/data/data/data_7.csv")
data

,n_days,N_last,N_first,N_diff_positive,N_diff_negative,pop_sum_mean,pop_sum_std,pop_mean_mean,pop_mean_std,norm2_mean_mean,...,hunos,romanos_increase,germanos_increase,galos_increase,egipcios_increase,hunos_increase,rs_day_last,p_play,p_play_weekend,p_play_week
0,7,3,2,1.0,0.0,1013.714286,257.146336,370.380952,45.911621,47.580120,...,0,0,0,1,0,0,16,0.857143,0.5,1.0
1,7,17,16,1.0,0.0,12741.428571,418.476944,762.258403,6.744138,62.318751,...,0,1,0,0,0,0,137,1.000000,1.0,1.0
2,7,3,3,0.0,0.0,1611.857143,111.475601,537.285714,37.158534,191.223381,...,3,0,0,0,0,0,16,1.000000,1.0,1.0
3,7,2,2,0.0,0.0,369.428571,5.563486,184.714286,2.781743,117.222537,...,0,0,0,0,0,0,13,0.428571,0.5,0.4
4,7,1,1,0.0,0.0,214.285714,22.932613,214.285714,22.932613,94.831429,...,0,0,0,0,0,0,30,0.714286,0.5,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117747,7,1,1,0.0,0.0,372.285714,132.022365,372.285714,132.022365,149.187801,...,0,0,0,0,0,0,16,0.571429,0.5,0.6
117748,7,2,1,1.0,0.0,474.571429,114.277232,283.285714,36.341961,110.448218,...,0,0,0,1,0,0,30,0.857143,1.0,0.8
117749,7,1,1,0.0,0.0,205.142857,27.051978,205.142857,27.051978,100.801786,...,0,0,0,0,0,0,35,1.000000,1.0,1.0
117750,7,2,2,0.0,0.0,322.142857,34.681544,161.071429,17.340772,113.135773,...,0,0,0,0,0,0,32,0.714286,0.0,1.0
117751,7,7,5,3.0,-1.0,2727.571429,182.776601,481.306122,40.367787,133.324710,...,0,0,0,2,0,0,23,0.285714,0.5,0.2

## Cluster

In [6]:
%%time
Z = hierarchy.linkage(data, method='single', metric='euclidean', optimal_ordering=True)

MemoryError: Unable to allocate 51.7 GiB for an array with shape (6932707876,) and data type float64

In [ ]:
#Save clustering

### Plot

In [ ]:
dn = hierarchy.dendrogram(Z)